### ISSUE TITLE
More specific read.me

### ISSUE THREAD

**Issue by gokberkoguz** [reaper7/XIAOMI_YI_MODE_SWITCH#1]
Hello,

I'm new in programming and action cams both. And i'm trying to use xiaomi yi as client. And i have no idea what did you write in read.me. Can you be more specific, please.

**Comment by reaper7** [comment]
Sorry but this project isn't currently developed - no time for this.

**Comment by gokberkoguz** [comment]
Sad, 

Thank you for the fast response though
